spring.application.name=hennovo-backend
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.docker.compose.enabled=false


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

rate-limit.cleanup-interval-ms=${RATE_LIMIT_CLEANUP_INTERVAL_MS:300000}

# LogHub
loghub.url=${LOGHUB_URL:http://localhost:8081}
loghub.api-key=${LOGHUB_API_KEY:}
loghub.app-id=${LOGHUB_APP_ID:}
